# Flutter 분석 설정 파일
# 코드 품질과 일관성을 위한 규칙을 정의합니다.

include: package:flutter_lints/flutter.yaml

analyzer:
  # 제외할 파일 경로
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "**/generated_plugin_registrant.dart"
    - "build/**"
    - "ios/**"
    - "android/**"
    - "web/**"
    - "test/.test_coverage.dart"
  
  # 오류 수준 설정
  errors:
    # 경고를 오류로 처리하지 않음
    avoid_print: warning
    prefer_const_constructors: warning
    prefer_const_literals_to_create_immutables: warning
    
    # 중요한 규칙은 오류로 처리
    invalid_assignment: error
    invalid_reference_to_this: error
    missing_required_param: error
    
    # 사용되지 않는 import 경고
    unused_import: warning
    unused_local_variable: warning
    
  language:
    # 실험적 기능 활성화
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    # Dart 스타일 가이드 준수
    - prefer_single_quotes
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    
    # 코드 품질
    - avoid_print
    - avoid_unnecessary_containers
    - avoid_web_libraries_in_flutter
    - no_logic_in_create_state
    - prefer_relative_imports
    - sort_constructors_first
    - use_build_context_synchronously
    - use_key_in_widget_constructors
    
    # 성능 최적화
    - avoid_function_literals_in_foreach_calls
    - prefer_collection_literals
    - prefer_if_null_operators
    - prefer_null_aware_operators
    - prefer_spread_collections
    
    # 보안
    - avoid_dynamic_calls
    - close_sinks
    - cancel_subscriptions
    
    # 접근성
    - use_colored_box
    - sized_box_for_whitespace
    - avoid_returning_null_for_void
    
    # 문서화 (MVP에서는 비활성화, 프로덕션에서는 활성화 권장)
    # - public_member_api_docs
    
    # 예외 처리
    - only_throw_errors
    - use_rethrow_when_possible
    
    # 비동기 처리
    - avoid_void_async
    - unawaited_futures
    
    # 금지 규칙들 (성능상 문제가 있을 수 있는 패턴들)
    - avoid_slow_async_io
    - avoid_types_as_parameter_names
    - control_flow_in_finally
    - empty_catches
    - empty_constructor_bodies
    - library_private_types_in_public_api
    - no_adjacent_strings_in_list
    - no_duplicate_case_values
    - prefer_void_to_null
    - throw_in_finally
    - unnecessary_statements
    - unrelated_type_equality_checks
    - use_super_parameters
