name: ittem_app
description: "Local item rental and trading platform - MVP"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # State Management
  flutter_riverpod: ^2.5.1
  
  # Navigation
  go_router: ^14.2.7
  
  # Maps & Location
  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  
  # Backend
  supabase_flutter: ^2.8.2
  
  # Image & Upload
  image_picker: ^1.1.2
  flutter_image_compress: ^2.3.0
  
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Forms & Models
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  
  # Payment - WebView for PortOne
  flutter_inappwebview: ^6.1.5
  
  # UI & Utils
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  permission_handler: ^11.3.1
  uuid: ^4.5.1
  url_launcher: ^6.3.1
  logger: ^2.4.0
  intl: ^0.19.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code generation
  build_runner: ^2.4.13
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true